# Intro to Linear Algebra
This topic, Intro to Linear Algebra, is the first in the Machine Learning Foundations series.

It is essential because linear algebra lies at the heart of most machine learning approaches and is especially predominant in deep learning, the branch of ML at the forefront of today’s artificial intelligence advances. Through the measured exposition of theory paired with interactive examples, you’ll develop an understanding of how linear algebra is used to solve for unknown values in high-dimensional spaces, thereby enabling machines to recognize patterns and make predictions.

The content covered in Intro to Linear Algebra is itself foundational for all the other topics in the Machine Learning Foundations series and it is especially relevant to Linear Algebra II.



## Scalars (Rank 0 Tensors) in Base Python

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x=25
x

25

In [5]:
type(x) #if we'd like more specificity (e.g., int16, uint8), we need NumPy or another numeric library

int

In [6]:
y=3

In [7]:
py_sum=x+y
py_sum

28

In [8]:
type(py_sum)

int

In [9]:
x_float =25.0
float_sum=x_float+y
float_sum

28.0

In [11]:
type(float_sum)

float

## Scalars in PyTorch
- PyTorch and TensorFlow are the two most popular automatic differentiation libraries (a focus of the Calculus I and Calculus II subjects in the ML Foundations series) in Python, itself the most popular programming language in ML
- PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays
- The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU

In [13]:
import torch

In [15]:
x_pt=torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [23]:
x_pt=torch.tensor(25, dtype=torch.float16)
x_pt

tensor(25., dtype=torch.float16)

In [16]:
x_pt.shape #scalars no dimention

torch.Size([])

In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.tensor(np.array([[1,2,3],[4,5,6]]))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

- The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [21]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x[1][2])

tensor(6)


In [22]:
x[0][1]=8
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


## Scalars in TensorFlow
tensors created with wrapper
- tf.Variable
- tf.constant
- tf.placeholder
- tf.SparseTensor
Most widely used if <code>tf.Variable</code>


In [25]:
import tensorflow as tf

In [26]:
x=tf.Variable(25)

In [27]:
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

In [28]:
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>


In [29]:
x =tf.constant(34)

In [30]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [31]:
y=tf.constant(50)

In [32]:
y

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [33]:
sum_=tf.add(x,y)
sum_

<tf.Tensor: shape=(), dtype=int32, numpy=84>

In [34]:
sum_.shape

TensorShape([])

In [35]:
x=tf.constant([1,2,3])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [36]:
x[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [37]:
x=tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [38]:
x[0][1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [41]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## Vectors(Rank 1 tensors, 1-D) in Numpy

In [42]:
import numpy as np

In [45]:
x=np.array([1,2,3]) #type argument is optional e.g: dtype=np.float16
x

array([1, 2, 3])

In [46]:
len(x)

3

In [47]:
x.shape

(3,)

In [48]:
type(x)

numpy.ndarray

In [49]:
x[0]

1

In [50]:
type(x[0])

numpy.int32

In [52]:
x[0]=6

In [53]:
x

array([6, 2, 3])

In [54]:
x=np.array([1,2,3],dtype=np.float16)
x

array([1., 2., 3.], dtype=float16)

In [55]:
x[0]

1.0

In [56]:
type(x[0])

numpy.float16

### Vector Transposition

In [57]:
# Transposing a regular 1-D array has no effect:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [58]:
x_t=x.T

In [59]:
x_t

array([1, 2, 3])

In [61]:
x.shape

(3,)

In [62]:
x_t.shape

(3,)

In [63]:
# ...but it does we use nested "matrix-style" brackets:
y=np.array([[25,3,5]])
y

array([[25,  3,  5]])

In [64]:
y.shape

(1, 3)

In [65]:
y_t=y.T

In [66]:
y_t

array([[25],
       [ 3],
       [ 5]])

In [67]:
y_t.shape

(3, 1)

## Zero Vectors
Has no effect if added to another vector

In [68]:
#creation
z=np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch and TensorFlow

In [71]:
import torch
import tensorflow as tf

In [72]:
x_pt=torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [73]:
x_tf=tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

## Norm : $L^2$ Norm
$L^2$ Norm measures simple (euclidean) distance from origin

In [74]:
x=np.array([1,2,3])

In [75]:
x

array([1, 2, 3])

In [80]:
(1**2+2**2+3**2)**0.5

3.7416573867739413

In [81]:
np.linalg.norm(x)

3.7416573867739413

So, if units in this 3-dimentional vector space are meters, then the vector x has a legth of 3.741

## Norm: $L^1$ Norm